language: python
python:
  - "3.8"
install:
  - pip install pybuilder
  - pip install codecov
  - pip install pytest-cov
script:
  - pyb
  - pytest --cov-report=xml --cov=movierecommender src/unittest/python/
after_success:
  - codecov